apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotmqttsender
  namespace: aks-workshop-dev
spec:
  selector:
      matchLabels:
        app: iotmqttsender
  replicas: 10
  template:
      metadata:
        labels:
          app: iotmqttsender
      spec:
        containers:
        - name: iotmqttsender
          image: akswkshpacr.azurecr.io/iotmqttsender:v1.0.2
          imagePullPolicy: IfNotPresent          
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: aks-workshop-secret
        nodeSelector:
          agentpool: iotnodepool