apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exch-devuat-manager-roles
  namespace: exch-devuat-dev
rules:
- apiGroups: ["", "apiextensions.k8s.io", "apps", "autoscaling", "batch", "events.k8s.io", "networking.k8s.io", "policy", "rbac.authorization.k8s.io", "scheduling.k8s.io"]
  resources: ["configmaps", "endpoints", "events", "limitranges", "persistentvolumeclaims", "pods", "resourcequotas", "serviceaccounts", "namespaces", "services", "customresourcedefinitions", "daemonsets", "deployments", "replicasets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs", "events", "ingresses", "networkpolicies", "poddisruptionbudgets", "rolebindings", "roles", "priorityclasses"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exch-devuat-manager-role-bindings
  namespace: exch-devuat-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exch-devuat-manager-roles
subjects:
- apiGroup: rbac.authorization.k8s.io
  name: 94c1bae6-307a-44ce-bb5f-0fd89c2e4a01
  kind: Group
  namespace: exch-devuat-dev