apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: captureorder
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: captureorder
  minReplicas: 1
  maxReplicas: 50
  metrics:    
  - type: Resource
    resource:
      name: cpu
      target:
       type: Utilization
       averageUtilization: 70