apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aks-workshop-roles
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-workshop-rolebindings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-workshop-roles
subjects:
  - apiGroup: rbac.authorization.k8s.io
    name: 08401348-c9a8-43a6-b6e6-49748f28c66c
    kind: User
    namespace: default
